services:

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - pyroscope
    networks:
      - grafana_network

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - 4040:4040
    networks:
      - grafana_network

  sample_app:
    build:
      context: ./sample_app
      dockerfile: Dockerfile
    environment:
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    networks:
      - grafana_network

volumes:
  grafana_data:
    driver: local

networks:
  grafana_network:
    driver: bridge

