global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'metrics_generator'
    static_configs:
      - targets: ['metrics_generator:9100']
    scrape_interval: 2s
    scrape_timeout: 1s