services:

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - grafana_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/loki.yml
    networks:
      - grafana_network


  log-generator:
    build:
      context: ./log-generator
      dockerfile: Dockerfile
    container_name: log-generator
    networks:
      - grafana_network
    depends_on:
      - loki

volumes:
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local

networks:
  grafana_network:
    driver: bridge

