{
 "title": "Simple logs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs per service",
   "type": "piechart",
   "gridPos": { "h": 29, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({job=\"log-generator\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{severity=\"error\"}"
    }
   ]
  },
  {
   "title": "Error log rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (rate({severity=\"critical\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Log tail",
   "type": "logs",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"log-generator\"}"
    }
   ]
  }
 ]
}